-- dropTables.sql
-- סדר המחיקה: מהילדים להורים (לפי תלויות FK)

DROP TABLE IF EXISTS CHECK_INS_OUTS;
DROP TABLE IF EXISTS ROOM_ASSIGNMENTS;
DROP TABLE IF EXISTS BOOKINGS;
DROP TABLE IF EXISTS GUESTS;
DROP TABLE IF EXISTS BOOKING_SOURCES;
DROP TABLE IF EXISTS ROOMS;
DROP TABLE IF EXISTS ROOM_TYPES;