-- selectAll.sql
-- בחירת כל הנתונים מכל טבלה

SELECT * FROM ROOM_TYPES;

SELECT * FROM ROOMS;

SELECT * FROM BOOKING_SOURCES;

SELECT * FROM GUESTS;

SELECT * FROM BOOKINGS;

SELECT * FROM ROOM_ASSIGNMENTS;

SELECT * FROM CHECK_INS_OUTS;